{"name": "test_login_error[logins_data3]", "status": "passed", "attachments": [{"name": "log", "source": "d077928f-2340-4cbe-8c78-50a99bf14f30-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "logins_data", "value": "{'username': 'yang', 'password': 123456, 'code': 1234, 'des': '验证码错误', 'expect': '验证码输入错误!', 'result': 300}"}], "start": 1596036761784, "stop": 1596036762433, "uuid": "c842626f-531e-45a6-9ead-a65de0ef017c", "historyId": "397928278f182cca9f41beffbf4abdaa", "testCaseId": "d696b25ca08475d04e305c9ec05fe006", "fullName": "TestCase.test_login.TestLogin#test_login_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('in_web', 'logins_data')"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-F7KFRCJP"}, {"name": "thread", "value": "20784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}