{"name": "test_login_error[logins_data3]", "status": "passed", "attachments": [{"name": "log", "source": "5961cd5b-3b5d-401e-8296-b6b3f8a5a792-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "logins_data", "value": "{'username': 'yang', 'password': 123456, 'code': 1234, 'des': '验证码错误', 'expect': '验证码输入错误!', 'result': 300}"}], "start": 1596195318478, "stop": 1596195319227, "uuid": "9c583668-c9d5-4634-9ad9-8c40a55adbf6", "historyId": "397928278f182cca9f41beffbf4abdaa", "testCaseId": "d696b25ca08475d04e305c9ec05fe006", "fullName": "TestCase.test_login.TestLogin#test_login_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('in_web', 'logins_data')"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-F7KFRCJP"}, {"name": "thread", "value": "10168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}